// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `Player.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include "../include/Player.h"
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_Player_VlcPlayer_ids[2] =
{
    "::Ice::Object",
    "::Player::VlcPlayer"
};
const ::std::string iceC_Player_VlcPlayer_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "play"
};
const ::std::string iceC_Player_VlcPlayer_play_name = "play";

}

bool
Player::VlcPlayer::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Player_VlcPlayer_ids, iceC_Player_VlcPlayer_ids + 2, s);
}

::std::vector<::std::string>
Player::VlcPlayer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_Player_VlcPlayer_ids[0], &iceC_Player_VlcPlayer_ids[2]);
}

::std::string
Player::VlcPlayer::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Player::VlcPlayer::ice_staticId()
{
    static const ::std::string typeId = "::Player::VlcPlayer";
    return typeId;
}

bool
Player::VlcPlayer::_iceD_play(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_trackName;
    istr->readAll(iceP_trackName);
    inS.endReadParams();
    ::std::string ret = this->play(::std::move(iceP_trackName), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}

bool
Player::VlcPlayer::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Player_VlcPlayer_ops, iceC_Player_VlcPlayer_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Player_VlcPlayer_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_play(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
Player::VlcPlayerPrx::_iceI_play(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::std::string>>& outAsync, const ::std::string& iceP_trackName, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_Player_VlcPlayer_play_name);
    outAsync->invoke(iceC_Player_VlcPlayer_play_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_trackName);
        },
        nullptr);
}

::std::shared_ptr<::Ice::ObjectPrx>
Player::VlcPlayerPrx::_newInstance() const
{
    return ::IceInternal::createProxy<VlcPlayerPrx>();
}

const ::std::string&
Player::VlcPlayerPrx::ice_staticId()
{
    return Player::VlcPlayer::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_Player_VlcPlayer_play_name = "play";

}
::IceProxy::Ice::Object* ::IceProxy::Player::upCast(::IceProxy::Player::VlcPlayer* p) { return p; }

void
::IceProxy::Player::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ::IceProxy::Player::VlcPlayer>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Player::VlcPlayer;
        v->_copyFrom(proxy);
    }
}

::Ice::AsyncResultPtr
IceProxy::Player::VlcPlayer::_iceI_begin_play(const ::std::string& iceP_trackName, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_Player_VlcPlayer_play_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Player_VlcPlayer_play_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Player_VlcPlayer_play_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_trackName);
        result->endWriteParams();
        result->invoke(iceC_Player_VlcPlayer_play_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::std::string
IceProxy::Player::VlcPlayer::end_play(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_Player_VlcPlayer_play_name);
    ::std::string ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::IceProxy::Ice::Object*
IceProxy::Player::VlcPlayer::_newInstance() const
{
    return new VlcPlayer;
}

const ::std::string&
IceProxy::Player::VlcPlayer::ice_staticId()
{
    return ::Player::VlcPlayer::ice_staticId();
}

Player::VlcPlayer::~VlcPlayer()
{
}

::Ice::Object* Player::upCast(::Player::VlcPlayer* p) { return p; }


namespace
{
const ::std::string iceC_Player_VlcPlayer_ids[2] =
{
    "::Ice::Object",
    "::Player::VlcPlayer"
};

}

bool
Player::VlcPlayer::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Player_VlcPlayer_ids, iceC_Player_VlcPlayer_ids + 2, s);
}

::std::vector< ::std::string>
Player::VlcPlayer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_Player_VlcPlayer_ids[0], &iceC_Player_VlcPlayer_ids[2]);
}

const ::std::string&
Player::VlcPlayer::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Player::VlcPlayer::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Player::VlcPlayer";
    return typeId;
#else
    return iceC_Player_VlcPlayer_ids[1];
#endif
}

bool
Player::VlcPlayer::_iceD_play(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_trackName;
    istr->read(iceP_trackName);
    inS.endReadParams();
    ::std::string ret = this->play(iceP_trackName, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}

namespace
{
const ::std::string iceC_Player_VlcPlayer_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "play"
};

}

bool
Player::VlcPlayer::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Player_VlcPlayer_all, iceC_Player_VlcPlayer_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Player_VlcPlayer_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_play(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
Player::VlcPlayer::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    Ice::StreamWriter< ::Player::VlcPlayer, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
Player::VlcPlayer::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    Ice::StreamReader< ::Player::VlcPlayer, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}

void
Player::_icePatchObjectPtr(VlcPlayerPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Player::VlcPlayerPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Player::VlcPlayer::ice_staticId(), v);
    }
}

namespace Ice
{
}

#endif
